# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsXF3DC3tx8a1jQ1N47xHMw2veLwqdMd

Task 1: Read a File and Handle Errors
Problem Statement:  Write a Python program that:
1.   Opens and reads a text file named sample.txt.
2.   Prints its content line by line.
3.   Handles errors gracefully if the file does not exist.
"""

try:
  fileName = 'sample1.txt'
  with open(fileName,'r') as file1:
    fileData = file1.readlines()
    print("Reading file content")
    i=1
    for line in fileData:
      print(f'Line {i}: {line.strip()}')
      i=i+1
except FileNotFoundError:
  print(f"Error: The file '{fileName}' was not found")

"""Task 2: Write and Append Data to a File

Problem Statement: Write a Python program that:
1.   Takes user input and writes it to a file named output.txt.
2.   Appends additional data to the same file.
3.   Reads and displays the final content of the file.

"""

userInput = input("Enter text to write to the file: ")
fileNameOut = 'output.txt'
with open(fileNameOut,'w') as file2:
  try:
    fileOutput = file2.write(userInput+ "\n")
    print(f'Data successfully written to {fileNameOut}'+'\n')
  except:
    print("Error while writing file")
dataToAppend = input("Enter additional text to append: ")
with open(fileNameOut,'a') as file3:
  fileAppended= file3.write(dataToAppend + "\n")
  print("Data Successfully appended"+'\n')
with open(fileNameOut,'r') as file4:
  fileData = file4.read()
print(f'Final content of the {fileNameOut}:')
print(fileData.strip())